from .auth import *
from .user import *
from .admin import *
from .staff import *
from .course import *
from .semester import *
from .programme import *
from .assessment import *
from .initialize import *
from .courseStaff import *
from .clashDetection import *
from .courseOffering import *
from .courseProgramme import *
from .courseAssessment import *